### ISSUE TITLE
error: duplicate value for resource 'attr/size' with config ''

### ISSUE THREAD

**Issue by Hamed1984** [cafebazaar/CafeBazaarUnitySDK#1]
سلام
موقع بیلد این خطا رو میده 
error: duplicate value for resource 'attr/size' with config ''
اشکال از این فایل هست
**com.farsitel.bazaar.auth-1.0.0-alpha05**
وقتی این فایل و حذف کنم بازی بدون مشکل بیلد میشه

این هم کاملش
* What went wrong:
Execution failed for task ':launcher:mergeReleaseResources'.
> 1 exception was raised by workers:
  com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource compilation failed
  C:\Users\Hamed\.gradle\caches\transforms-2\files-2.1\c94306b7e101da89d81f9194b8e5f308\res\values\values.xml:162:5-167:221: AAPT: error: duplicate value for resource 'attr/size' with config ''.
      
  C:\Users\Hamed\.gradle\caches\transforms-2\files-2.1\c94306b7e101da89d81f9194b8e5f308\res\values\values.xml:162:5-167:221: AAPT: error: resource previously defined here.
      
  D:\Game Projects\EnemyNightmare 2\Temp\gradleOut\launcher\build\intermediates\incremental\mergeReleaseResources\merged.dir\values\values.xml: error: file failed to compile.

**Comment by Omid2999** [comment]
Get New Version  this bug is fixed now

**Comment by Hamed1984** [comment]
سلام
اون مشکل حل شد 
ولی ارور Authentication Failed میده

اون ClientID و Secret که در قسمت ورود به بازار برای هر برنامه مشخص شده کجا باید استفاده شود
در مستندات اشاره ای به آن نشده است

**Comment by sadegh-askari** [comment]
> سلام
> اون مشکل حل شد
> ولی ارور Authentication Failed میده
> 
> اون ClientID و Secret که در قسمت ورود به بازار برای هر برنامه مشخص شده کجا باید استفاده شود
> در مستندات اشاره ای به آن نشده است

سلام
در حال حاضر اون مقادیر بدون استفاده هستن
در ادامه هر وقت نیازی به اون ها باشه داخل مستندات، توضیحشون قرار داده میشه
با تشکر
